#ifndef _USER_LIBC_SYSCALL_H
#define _USER_LIBC_SYSCALL_H

#include <stdint.h>

#define SYSCALL_WRITE 1
#define SYSCALL_EXIT  2
#define SYSCALL_OPEN  3
#define SYSCALL_READ  4
#define SYSCALL_CLOSE 5
#define SYSCALL_EXEC  6
#define SYSCALL_GETARGS 7
#define SYSCALL_STAT  8
#define SYSCALL_SEEK  9
#define SYSCALL_LISTDIR 10
#define SYSCALL_MKDIR   11
#define SYSCALL_RM      12
#define SYSCALL_TOUCH   13
#define SYSCALL_GETCWD  14
#define SYSCALL_SETCWD  15
#define SYSCALL_CLEAR   16
#define SYSCALL_SETCOLOR 17
#define SYSCALL_WRITEFILE 18
#define SYSCALL_HISTORY_COUNT 19
#define SYSCALL_HISTORY_GET 20
#define SYSCALL_GET_TICKS 21
#define SYSCALL_GET_COMMAND_COUNT 22
#define SYSCALL_GETCHAR 23
#define SYSCALL_SLEEP_MS 24
#define SYSCALL_ALIAS_SET 25
#define SYSCALL_ALIAS_REMOVE 26
#define SYSCALL_ALIAS_COUNT 27
#define SYSCALL_ALIAS_GET 28
#define SYSCALL_TIMER_START 29
#define SYSCALL_TIMER_STOP 30
#define SYSCALL_TIMER_STATUS 31
#define SYSCALL_BEEP 32
#define SYSCALL_HALT 33
#define SYSCALL_GFX_DEMO 34
#define SYSCALL_GFX_ANIM 35
#define SYSCALL_GFX_PAINT 36
#define SYSCALL_GUI_DESKTOP 37
#define SYSCALL_GUI 38
#define SYSCALL_GUI_PAINT 39
#define SYSCALL_GUI_CALC 40
#define SYSCALL_GUI_FILEMGR 41
#define SYSCALL_GFX_SET_MODE 42
#define SYSCALL_GFX_GET_MODE 43
#define SYSCALL_GFX_GET_WIDTH 44
#define SYSCALL_GFX_GET_HEIGHT 45
#define SYSCALL_GFX_CLEAR 46
#define SYSCALL_GFX_PUTPIXEL 47
#define SYSCALL_GFX_DRAW_RECT 48
#define SYSCALL_GFX_FILL_RECT 49
#define SYSCALL_GFX_DRAW_LINE 50
#define SYSCALL_GFX_DRAW_CHAR 51
#define SYSCALL_GFX_PRINT 52
#define SYSCALL_GFX_FLIP 53
#define SYSCALL_GFX_DOUBLEBUFFER_ENABLE 54
#define SYSCALL_GFX_DOUBLEBUFFER_DISABLE 55
#define SYSCALL_MOUSE_GET_STATE 56
#define SYSCALL_KEYBOARD_HAS_INPUT 57
#define SYSCALL_RENAME 58
#define SYSCALL_SPAWN 59
#define SYSCALL_WAIT 60
#define SYSCALL_FORK 61
#define SYSCALL_GFX_BLIT 62
#define SYSCALL_KEY_REPEAT 63
#define SYSCALL_SPEAKER_START 64
#define SYSCALL_SPEAKER_STOP 65
#define SYSCALL_FS_FREE_BLOCKS 66
#define SYSCALL_HEAP_STATS 67
#define SYSCALL_PROCESS_COUNT 68
#define SYSCALL_PROCESS_LIST 69
#define SYSCALL_INSTALL_EMBEDDED 70
#define SYSCALL_BRK 71
#define SYSCALL_PIPE 72
#define SYSCALL_DUP2 73
#define SYSCALL_KILL 74
#define SYSCALL_AUDIO_WRITE 75
#define SYSCALL_AUDIO_SET_VOLUME 76
#define SYSCALL_AUDIO_GET_VOLUME 77
#define SYSCALL_AUDIO_STATUS 78

static inline int syscall3(int num, uint32_t a, uint32_t b, uint32_t c) {
	int ret;
	__asm__ volatile ("int $0x80"
		: "=a"(ret)
		: "a"(num), "b"(a), "c"(b), "d"(c)
		: "memory");
	return ret;
}

#endif
